spring:
  datasource:
    url: jdbc:mysql://101.42.30.159:3306/shmhs
    password: ${PASSWORD}
    username: root
  data:
    redis:
      host: 101.42.30.159
      password: ${PASSWORD}
      cluster:
        nodes:
          - 101.42.30.159:6371
          - 101.42.30.159:6372
          - 101.42.30.159:6373
          - 101.42.30.159:6374
          - 101.42.30.159:6375
          - 101.42.30.159:6376
  boot:
    admin:
      client:
        url: http://admin.pi1grim.top
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - logfile
          - info
          - heapdump
          - threaddump
          - metrics
          - conditions
logging:
  file:
    name: boot.log
    path: /var/log/boot-ea.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
server:
  servlet:
    context-path: /ea
  port: 8081